# Generated by Django 5.0.2 on 2024-06-20 00:31

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_carouselimage_comingsoon_leftimage_rightimage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='info',
            field=ckeditor.fields.RichTextField(null=True),
        ),
    ]
